// Code generated by protoc-gen-gogo.
// source: byzantine.proto
// DO NOT EDIT!

/*
	Package byzantine is a generated protocol buffer package.

	It is generated from these files:
		byzantine.proto

	It has these top-level messages:
		Publication
		PublicationIndex
		DataLocation
		Publisher
		Subscriber
		PubResponse
		NewClusterMember
		EchoMessage
*/
package byzantine

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// / Publication is the message sent out to the broker.
type Publication struct {
	PublicationID string     `protobuf:"bytes,1,opt,name=PublicationID,proto3" json:"PublicationID,omitempty"`
	BrokerID      string     `protobuf:"bytes,2,opt,name=BrokerID,proto3" json:"BrokerID,omitempty"`
	Contents      []byte     `protobuf:"bytes,3,opt,name=Contents,proto3" json:"Contents,omitempty"`
	Sender        *Publisher `protobuf:"bytes,4,opt,name=Sender" json:"Sender,omitempty"`
}

func (m *Publication) Reset()                    { *m = Publication{} }
func (m *Publication) String() string            { return proto.CompactTextString(m) }
func (*Publication) ProtoMessage()               {}
func (*Publication) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{0} }

func (m *Publication) GetPublicationID() string {
	if m != nil {
		return m.PublicationID
	}
	return ""
}

func (m *Publication) GetBrokerID() string {
	if m != nil {
		return m.BrokerID
	}
	return ""
}

func (m *Publication) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Publication) GetSender() *Publisher {
	if m != nil {
		return m.Sender
	}
	return nil
}

// / PublicationIndex is the cache pointer of where data actually lives.
type PublicationIndex struct {
	Index string          `protobuf:"bytes,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Nodes []*DataLocation `protobuf:"bytes,2,rep,name=Nodes" json:"Nodes,omitempty"`
}

func (m *PublicationIndex) Reset()                    { *m = PublicationIndex{} }
func (m *PublicationIndex) String() string            { return proto.CompactTextString(m) }
func (*PublicationIndex) ProtoMessage()               {}
func (*PublicationIndex) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{1} }

func (m *PublicationIndex) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *PublicationIndex) GetNodes() []*DataLocation {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type DataLocation struct {
	Node  string `protobuf:"bytes,1,opt,name=Node,proto3" json:"Node,omitempty"`
	Start uint64 `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	Stop  uint64 `protobuf:"varint,3,opt,name=Stop,proto3" json:"Stop,omitempty"`
}

func (m *DataLocation) Reset()                    { *m = DataLocation{} }
func (m *DataLocation) String() string            { return proto.CompactTextString(m) }
func (*DataLocation) ProtoMessage()               {}
func (*DataLocation) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{2} }

func (m *DataLocation) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *DataLocation) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *DataLocation) GetStop() uint64 {
	if m != nil {
		return m.Stop
	}
	return 0
}

// / Publisher defines a publisher within a quorum.
type Publisher struct {
	Address     string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	PublisherID string `protobuf:"bytes,2,opt,name=PublisherID,proto3" json:"PublisherID,omitempty"`
}

func (m *Publisher) Reset()                    { *m = Publisher{} }
func (m *Publisher) String() string            { return proto.CompactTextString(m) }
func (*Publisher) ProtoMessage()               {}
func (*Publisher) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{3} }

func (m *Publisher) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Publisher) GetPublisherID() string {
	if m != nil {
		return m.PublisherID
	}
	return ""
}

// / Subscriber defines a subscriber within a subscriber pool.
type Subscriber struct {
	Address                    string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	PoolID                     uint64 `protobuf:"varint,2,opt,name=PoolID,proto3" json:"PoolID,omitempty"`
	DestinationDistinguishment uint64 `protobuf:"varint,3,opt,name=DestinationDistinguishment,proto3" json:"DestinationDistinguishment,omitempty"`
}

func (m *Subscriber) Reset()                    { *m = Subscriber{} }
func (m *Subscriber) String() string            { return proto.CompactTextString(m) }
func (*Subscriber) ProtoMessage()               {}
func (*Subscriber) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{4} }

func (m *Subscriber) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Subscriber) GetPoolID() uint64 {
	if m != nil {
		return m.PoolID
	}
	return 0
}

func (m *Subscriber) GetDestinationDistinguishment() uint64 {
	if m != nil {
		return m.DestinationDistinguishment
	}
	return 0
}

// / PubResponse returns whether or not the data was actually stored.
type PubResponse struct {
	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (m *PubResponse) Reset()                    { *m = PubResponse{} }
func (m *PubResponse) String() string            { return proto.CompactTextString(m) }
func (*PubResponse) ProtoMessage()               {}
func (*PubResponse) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{5} }

func (m *PubResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// / NewClusterMember is how new Pub/Subs join the pool
type NewClusterMember struct {
	PublisherID uint64 `protobuf:"varint,1,opt,name=PublisherID,proto3" json:"PublisherID,omitempty"`
	BrokerID    uint64 `protobuf:"varint,2,opt,name=BrokerID,proto3" json:"BrokerID,omitempty"`
}

func (m *NewClusterMember) Reset()                    { *m = NewClusterMember{} }
func (m *NewClusterMember) String() string            { return proto.CompactTextString(m) }
func (*NewClusterMember) ProtoMessage()               {}
func (*NewClusterMember) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{6} }

func (m *NewClusterMember) GetPublisherID() uint64 {
	if m != nil {
		return m.PublisherID
	}
	return 0
}

func (m *NewClusterMember) GetBrokerID() uint64 {
	if m != nil {
		return m.BrokerID
	}
	return 0
}

// / Heartbeat is how we determine who is alive and who isn't.
type EchoMessage struct {
	Hello        bool   `protobuf:"varint,1,opt,name=Hello,proto3" json:"Hello,omitempty"`
	MessageIdent string `protobuf:"bytes,2,opt,name=MessageIdent,proto3" json:"MessageIdent,omitempty"`
}

func (m *EchoMessage) Reset()                    { *m = EchoMessage{} }
func (m *EchoMessage) String() string            { return proto.CompactTextString(m) }
func (*EchoMessage) ProtoMessage()               {}
func (*EchoMessage) Descriptor() ([]byte, []int) { return fileDescriptorByzantine, []int{7} }

func (m *EchoMessage) GetHello() bool {
	if m != nil {
		return m.Hello
	}
	return false
}

func (m *EchoMessage) GetMessageIdent() string {
	if m != nil {
		return m.MessageIdent
	}
	return ""
}

func init() {
	proto.RegisterType((*Publication)(nil), "byzantine.Publication")
	proto.RegisterType((*PublicationIndex)(nil), "byzantine.PublicationIndex")
	proto.RegisterType((*DataLocation)(nil), "byzantine.DataLocation")
	proto.RegisterType((*Publisher)(nil), "byzantine.Publisher")
	proto.RegisterType((*Subscriber)(nil), "byzantine.Subscriber")
	proto.RegisterType((*PubResponse)(nil), "byzantine.PubResponse")
	proto.RegisterType((*NewClusterMember)(nil), "byzantine.NewClusterMember")
	proto.RegisterType((*EchoMessage)(nil), "byzantine.EchoMessage")
}
func (m *Publication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Publication) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PublicationID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.PublicationID)))
		i += copy(dAtA[i:], m.PublicationID)
	}
	if len(m.BrokerID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.BrokerID)))
		i += copy(dAtA[i:], m.BrokerID)
	}
	if len(m.Contents) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.Contents)))
		i += copy(dAtA[i:], m.Contents)
	}
	if m.Sender != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(m.Sender.Size()))
		n1, err := m.Sender.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func (m *PublicationIndex) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PublicationIndex) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.Index)))
		i += copy(dAtA[i:], m.Index)
	}
	if len(m.Nodes) > 0 {
		for _, msg := range m.Nodes {
			dAtA[i] = 0x12
			i++
			i = encodeVarintByzantine(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *DataLocation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataLocation) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Node) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.Node)))
		i += copy(dAtA[i:], m.Node)
	}
	if m.Start != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(m.Start))
	}
	if m.Stop != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(m.Stop))
	}
	return i, nil
}

func (m *Publisher) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Publisher) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.Address)))
		i += copy(dAtA[i:], m.Address)
	}
	if len(m.PublisherID) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.PublisherID)))
		i += copy(dAtA[i:], m.PublisherID)
	}
	return i, nil
}

func (m *Subscriber) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Subscriber) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.Address)))
		i += copy(dAtA[i:], m.Address)
	}
	if m.PoolID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(m.PoolID))
	}
	if m.DestinationDistinguishment != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(m.DestinationDistinguishment))
	}
	return i, nil
}

func (m *PubResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PubResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Success {
		dAtA[i] = 0x8
		i++
		if m.Success {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *NewClusterMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NewClusterMember) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.PublisherID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(m.PublisherID))
	}
	if m.BrokerID != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(m.BrokerID))
	}
	return i, nil
}

func (m *EchoMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EchoMessage) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Hello {
		dAtA[i] = 0x8
		i++
		if m.Hello {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.MessageIdent) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintByzantine(dAtA, i, uint64(len(m.MessageIdent)))
		i += copy(dAtA[i:], m.MessageIdent)
	}
	return i, nil
}

func encodeFixed64Byzantine(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Byzantine(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintByzantine(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Publication) Size() (n int) {
	var l int
	_ = l
	l = len(m.PublicationID)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	l = len(m.BrokerID)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	l = len(m.Contents)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	if m.Sender != nil {
		l = m.Sender.Size()
		n += 1 + l + sovByzantine(uint64(l))
	}
	return n
}

func (m *PublicationIndex) Size() (n int) {
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovByzantine(uint64(l))
		}
	}
	return n
}

func (m *DataLocation) Size() (n int) {
	var l int
	_ = l
	l = len(m.Node)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	if m.Start != 0 {
		n += 1 + sovByzantine(uint64(m.Start))
	}
	if m.Stop != 0 {
		n += 1 + sovByzantine(uint64(m.Stop))
	}
	return n
}

func (m *Publisher) Size() (n int) {
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	l = len(m.PublisherID)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	return n
}

func (m *Subscriber) Size() (n int) {
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	if m.PoolID != 0 {
		n += 1 + sovByzantine(uint64(m.PoolID))
	}
	if m.DestinationDistinguishment != 0 {
		n += 1 + sovByzantine(uint64(m.DestinationDistinguishment))
	}
	return n
}

func (m *PubResponse) Size() (n int) {
	var l int
	_ = l
	if m.Success {
		n += 2
	}
	return n
}

func (m *NewClusterMember) Size() (n int) {
	var l int
	_ = l
	if m.PublisherID != 0 {
		n += 1 + sovByzantine(uint64(m.PublisherID))
	}
	if m.BrokerID != 0 {
		n += 1 + sovByzantine(uint64(m.BrokerID))
	}
	return n
}

func (m *EchoMessage) Size() (n int) {
	var l int
	_ = l
	if m.Hello {
		n += 2
	}
	l = len(m.MessageIdent)
	if l > 0 {
		n += 1 + l + sovByzantine(uint64(l))
	}
	return n
}

func sovByzantine(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozByzantine(x uint64) (n int) {
	return sovByzantine(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Publication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Publication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Publication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicationID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicationID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BrokerID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BrokerID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contents", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contents = append(m.Contents[:0], dAtA[iNdEx:postIndex]...)
			if m.Contents == nil {
				m.Contents = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sender == nil {
				m.Sender = &Publisher{}
			}
			if err := m.Sender.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PublicationIndex) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PublicationIndex: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PublicationIndex: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &DataLocation{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataLocation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataLocation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataLocation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Node = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Start", wireType)
			}
			m.Start = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Start |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stop", wireType)
			}
			m.Stop = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Stop |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Publisher) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Publisher: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Publisher: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublisherID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublisherID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Subscriber) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Subscriber: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Subscriber: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolID", wireType)
			}
			m.PoolID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationDistinguishment", wireType)
			}
			m.DestinationDistinguishment = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DestinationDistinguishment |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PubResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PubResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PubResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Success", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Success = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NewClusterMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NewClusterMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NewClusterMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublisherID", wireType)
			}
			m.PublisherID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublisherID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BrokerID", wireType)
			}
			m.BrokerID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BrokerID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EchoMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EchoMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EchoMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hello", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Hello = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MessageIdent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthByzantine
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MessageIdent = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipByzantine(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthByzantine
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipByzantine(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowByzantine
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowByzantine
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthByzantine
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowByzantine
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipByzantine(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthByzantine = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowByzantine   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("byzantine.proto", fileDescriptorByzantine) }

var fileDescriptorByzantine = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x75, 0xda, 0x6d, 0x6c, 0x6e, 0x22, 0x86, 0xa1, 0xe8, 0x12, 0x24, 0x2c, 0x83, 0x60, 0x1e,
	0xb4, 0x85, 0xfa, 0x2e, 0xd8, 0xae, 0xd4, 0x40, 0x5b, 0xc2, 0xec, 0x83, 0xcf, 0xfb, 0x71, 0x49,
	0x06, 0xb7, 0x33, 0x61, 0x66, 0x16, 0x3f, 0x1e, 0xfc, 0x0d, 0xbe, 0xfa, 0x8f, 0x7c, 0xf4, 0x27,
	0x48, 0xfc, 0x23, 0x32, 0xb3, 0x93, 0xed, 0x56, 0xa1, 0x6f, 0xf7, 0x9c, 0x39, 0x9c, 0x7b, 0xce,
	0x65, 0xe0, 0x71, 0xf1, 0xe5, 0x6b, 0x2e, 0xad, 0x90, 0x78, 0xbc, 0xd1, 0xca, 0x2a, 0x3a, 0xec,
	0x88, 0xe9, 0xb3, 0x95, 0x52, 0xab, 0x1a, 0x4f, 0xf2, 0x8d, 0x38, 0xc9, 0xa5, 0x54, 0x36, 0xb7,
	0x42, 0x49, 0xd3, 0x0a, 0xd9, 0x0f, 0x02, 0xa3, 0x65, 0x53, 0xd4, 0xa2, 0xf4, 0x34, 0x7d, 0x0e,
	0x8f, 0x7a, 0x70, 0x91, 0xc6, 0x24, 0x21, 0xf3, 0x21, 0xbf, 0x4b, 0xd2, 0x29, 0x1c, 0x9e, 0x69,
	0xf5, 0x11, 0xf5, 0x22, 0x8d, 0xf7, 0xbc, 0xa0, 0xc3, 0xee, 0xed, 0x5c, 0x49, 0x8b, 0xd2, 0x9a,
	0x78, 0x3f, 0x21, 0xf3, 0x31, 0xef, 0x30, 0x7d, 0x09, 0x83, 0x0c, 0x65, 0x85, 0x3a, 0x8e, 0x12,
	0x32, 0x1f, 0x9d, 0x1e, 0x1d, 0xdf, 0x06, 0xf7, 0x1b, 0xcc, 0x1a, 0x35, 0x0f, 0x1a, 0xf6, 0x01,
	0x26, 0xfd, 0xb5, 0xb2, 0xc2, 0xcf, 0xf4, 0x08, 0x0e, 0xfc, 0x10, 0x72, 0xb5, 0x80, 0xbe, 0x82,
	0x83, 0x6b, 0x55, 0xa1, 0x89, 0xf7, 0x92, 0xfd, 0xf9, 0xe8, 0xf4, 0x69, 0xcf, 0x36, 0xcd, 0x6d,
	0x7e, 0xa9, 0x5a, 0x0b, 0xde, 0xaa, 0xd8, 0x25, 0x8c, 0xfb, 0x34, 0xa5, 0x10, 0xb9, 0x87, 0xe0,
	0xe9, 0x67, 0xb7, 0x28, 0xb3, 0xb9, 0xb6, 0xbe, 0x5f, 0xc4, 0x5b, 0xe0, 0x94, 0x99, 0x55, 0x1b,
	0x5f, 0x2c, 0xe2, 0x7e, 0x66, 0x17, 0x30, 0xec, 0xb2, 0xd3, 0x18, 0x1e, 0xbe, 0xad, 0x2a, 0x8d,
	0xc6, 0x04, 0xb7, 0x1d, 0xa4, 0x49, 0x38, 0xb4, 0x93, 0x75, 0x67, 0xeb, 0x53, 0xec, 0x1b, 0x40,
	0xd6, 0x14, 0xa6, 0xd4, 0xa2, 0xb8, 0xd7, 0xe9, 0x09, 0x0c, 0x96, 0x4a, 0xd5, 0xc1, 0x24, 0xe2,
	0x01, 0xd1, 0x37, 0x30, 0x4d, 0xd1, 0x58, 0x21, 0x7d, 0xab, 0x54, 0xb8, 0x71, 0xd5, 0x08, 0xb3,
	0xbe, 0x41, 0x69, 0x43, 0xe4, 0x7b, 0x14, 0xec, 0x85, 0x4f, 0xc8, 0xd1, 0x6c, 0x94, 0x34, 0xe8,
	0x02, 0x64, 0x4d, 0x59, 0xee, 0x02, 0x1c, 0xf2, 0x1d, 0x64, 0x4b, 0x98, 0x5c, 0xe3, 0xa7, 0xf3,
	0xba, 0x31, 0x16, 0xf5, 0x15, 0xde, 0xb8, 0xb8, 0xff, 0xd4, 0x23, 0x7e, 0x5b, 0x9f, 0xfa, 0xef,
	0xd3, 0x44, 0xb7, 0x9f, 0x86, 0x5d, 0xc0, 0xe8, 0x5d, 0xb9, 0x56, 0x57, 0x68, 0x4c, 0xbe, 0xf2,
	0xc7, 0x7f, 0x8f, 0x75, 0xad, 0xc2, 0xe2, 0x16, 0x50, 0x06, 0xe3, 0x20, 0x58, 0x54, 0xae, 0x51,
	0x7b, 0xc2, 0x3b, 0xdc, 0xd9, 0xe4, 0xe7, 0x76, 0x46, 0x7e, 0x6d, 0x67, 0xe4, 0xf7, 0x76, 0x46,
	0xbe, 0xff, 0x99, 0x3d, 0x28, 0x06, 0xfe, 0xa3, 0xbf, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x31,
	0xda, 0x38, 0x7c, 0x24, 0x03, 0x00, 0x00,
}
